name: cinnamon_riverpod_2
description: "Riverpod Template"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod:
  hooks_riverpod:
  cupertino_icons: ^1.0.2
  go_router:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  equatable:
  hive_flutter:
  simple_logger:
  dio:
  purchases_flutter:
  flutter_hooks:
  flutter_map:
  flutter_svg: 
  flutter_form_builder:
  form_builder_validators:

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  riverpod_lint:
  flutter_lints:
  build_runner:
  flutter_gen_runner:


flutter:
  assets:
    - assets/icons/
    - assets/images/

  fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope-ExtraLight.ttf
      - asset: assets/fonts/Manrope-Light.ttf
      - asset: assets/fonts/Manrope-Medium.ttf
      - asset: assets/fonts/Manrope-Regular.ttf
      - asset: assets/fonts/Manrope-SemiBold.ttf
      - asset: assets/fonts/Manrope-Bold.ttf
      - asset: assets/fonts/Manrope-ExtraBold.ttf


  uses-material-design: true


