name: cinnamon_riverpod_2
description: "Cinnamon agency's Riverpod app template"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # State Management
  flutter_riverpod: ^3.0.0-dev.0
  hooks_riverpod:
  flutter_hooks:

  # Core services
  dio:
  firebase_core:
  firebase_auth:
  firebase_messaging:
  firebase_storage:
  cloud_firestore:
  flutter_local_notifications:
  purchases_flutter:
  hive_flutter:
  flutter_dotenv:

  # Utils
  app_settings:
  auto_size_text:
  permission_handler:
  simple_logger:
  timezone:
  equatable:
  collection:
  uuid:
  intl:
  cached_network_image:
  url_launcher:

  # UI
  cupertino_icons: ^1.0.2
  go_router:
  flutter_form_builder:
  form_builder_validators:
  flutter_svg:
  flutter_svg_provider:
  flutter_map:
  flutter_map_animations:
  latlong2:
  flutter_animate:
  flutter_datetime_picker_plus: ^2.1.0
  image_cropper:
  image_picker:
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint:
  riverpod_lint:
  flutter_lints:
  build_runner: # Trigger by running: dart run build_runner build --delete-conflicting-outputs
  flutter_gen_runner: # Trigger by running: flutter dart run build_runner build --delete-conflicting-outputs
  flutter_launcher_icons: # See config in flutter_launcher_icons.yaml


flutter:
  # This flag has to be true in order for gen-l10n to generate localizations
  generate: true
  
  assets:
    - assets/icons/
    - assets/images/
    - .env

  fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope-ExtraLight.ttf
      - asset: assets/fonts/Manrope-Light.ttf
      - asset: assets/fonts/Manrope-Medium.ttf
      - asset: assets/fonts/Manrope-Regular.ttf
      - asset: assets/fonts/Manrope-SemiBold.ttf
      - asset: assets/fonts/Manrope-Bold.ttf
      - asset: assets/fonts/Manrope-ExtraBold.ttf


  uses-material-design: true


