// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo5T0d7pjeHHsLVnG99Q7UpADNFeqtXx8',
    appId: '1:884763953749:web:d908ee3ec9a45fe78962dc',
    messagingSenderId: '884763953749',
    projectId: 'tripfindercinnamon',
    authDomain: 'tripfindercinnamon.firebaseapp.com',
    storageBucket: 'tripfindercinnamon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw9E7XlRACZdcsnKKQONRpMzasc4_J_Ps',
    appId: '1:884763953749:android:a52010bc002ccb828962dc',
    messagingSenderId: '884763953749',
    projectId: 'tripfindercinnamon',
    storageBucket: 'tripfindercinnamon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1rjBNyjYf96oDROaGhBA4dxoJTFnOWJs',
    appId: '1:884763953749:ios:74e7900aebbd403e8962dc',
    messagingSenderId: '884763953749',
    projectId: 'tripfindercinnamon',
    storageBucket: 'tripfindercinnamon.appspot.com',
    iosBundleId: 'agency.cinnamon.cinnamonRiverpod2',
  );
}
